# Generated by Django 4.1.1 on 2022-09-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_relationship_remove_tag_name_delete_scope_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(through='articles.Relationship', to='articles.article'),
        ),
    ]
