# Generated by Django 4.1.1 on 2022-09-26 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_remove_sensor_measurements_measurement_measurements'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='measurements',
            new_name='sensor',
        ),
    ]
