# Generated by Django 4.1 on 2022-09-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='Модель телефона')),
                ('price', models.FloatField(verbose_name='Стоимость телефона')),
                ('image', models.URLField(verbose_name='ссылка на изображение')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('lte_exists', models.BooleanField(verbose_name='Поддержка ЛТЕ')),
                ('slug', models.SlugField(unique=True, verbose_name='URL адресс модели')),
            ],
        ),
    ]
