# Generated by Django 4.1 on 2022-09-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(verbose_name='Наличие LTE'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название модели телефона'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='price',
            field=models.FloatField(verbose_name='Цена телфона'),
        ),
        migrations.AlterField(
            model_name='phone',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL адрес'),
        ),
    ]
